// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GLv0wT0WLbWly5rNLHF9zzlP_V1HXsI',
    appId: '1:664189180486:web:d58b7eab1d5bc776754847',
    messagingSenderId: '664189180486',
    projectId: 'study-first-56486',
    authDomain: 'study-first-56486.firebaseapp.com',
    storageBucket: 'study-first-56486.appspot.com',
    measurementId: 'G-YXFZL1G6RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEGms23j2k818VY0YQz8Am_wQn4wzErE',
    appId: '1:664189180486:android:b127232b0530f77f754847',
    messagingSenderId: '664189180486',
    projectId: 'study-first-56486',
    storageBucket: 'study-first-56486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogKKgp3NKINxRu0oC-tv-aS3FUfu8gLM',
    appId: '1:664189180486:ios:2ff3e4d62c7e6ccd754847',
    messagingSenderId: '664189180486',
    projectId: 'study-first-56486',
    storageBucket: 'study-first-56486.appspot.com',
    iosBundleId: 'com.example.studyFirstGgsLater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogKKgp3NKINxRu0oC-tv-aS3FUfu8gLM',
    appId: '1:664189180486:ios:c2b02b178154c48c754847',
    messagingSenderId: '664189180486',
    projectId: 'study-first-56486',
    storageBucket: 'study-first-56486.appspot.com',
    iosBundleId: 'com.example.studyFirstGgsLater.RunnerTests',
  );
}
