/// Flutter icons CustomGameIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomGameIcons
///      fonts:
///       - asset: fonts/CustomGameIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomGameIcons {
  CustomGameIcons._();

  static const _kFontFam = 'CustomGameIcons';
  static const String? _kFontPkg = null;

  static const IconData account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData treasure_chest = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sword_cross = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
